version : '3.7'

services:
  frontend:
    build: ./ClientAdminProjetServicesWeb/
    container_name: frontend_event_board
    ports: 
      - 4200:80
    depends_on:
      - backend
  backend:
    image: ${DOCKER_REGISTRY-}pfservice
    container_name: backend_event_board
    build: 
      context: ./PFService/
      dockerfile: PFservice/Dockerfile
    ports:
      - 5003:5003
      - 5002:5002
    environment:
      MYSQL_DB_USER: root
      MYSQL_DATABASE_NAME: projetevenements
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: db_event_board
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: projetevenements
    ports:
      - 3306:3306
    volumes:
      - ./db-start:/docker-entrypoint-initdb.d